In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/stepa/PycharmProjects/2_bookings.csv', sep = ';')

In [3]:
df.shape

(119390, 21)

In [4]:
df.describe()

,Is Canceled,Lead Time,Arrival Date Year,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,stays total nights,Adults,Children,Babies
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,3.427900,1.856403,0.103890,0.007949
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,2.557439,0.579261,0.398561,0.097436
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,2.000000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,3.000000,2.000000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,4.000000,2.000000,0.000000,0.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,69.000000,55.000000,10.000000,10.000000

In [5]:
df.dtypes

Hotel                            str
Is Canceled                    int64
Lead Time                      int64
arrival full date                str
Arrival Date Year              int64
Arrival Date Month               str
Arrival Date Week Number       int64
Arrival Date Day of Month      int64
Stays in Weekend nights        int64
Stays in week nights           int64
stays total nights             int64
Adults                         int64
Children                     float64
Babies                         int64
Meal                             str
Country                          str
Reserved Room Type               str
Assigned room type               str
customer type                    str
Reservation Status               str
Reservation status_date          str
dtype: object

In [6]:
df.head(7)

,Hotel,Is Canceled,Lead Time,arrival full date,Arrival Date Year,Arrival Date Month,Arrival Date Week Number,Arrival Date Day of Month,Stays in Weekend nights,Stays in week nights,...,Adults,Children,Babies,Meal,Country,Reserved Room Type,Assigned room type,customer type,Reservation Status,Reservation status_date
0,Resort Hotel,0,342,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015-07-01,2015,July,27,1,0,0,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,C,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015-07-01,2015,July,27,1,0,1,...,1,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,GBR,A,A,Transient,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015-07-01,2015,July,27,1,0,2,...,2,0.0,0,BB,PRT,C,C,Transient,Check-Out,2015-07-03

In [7]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [8]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_full_date',
       'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'stays_total_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'reserved_room_type', 'assigned_room_type',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='str')

In [9]:
successful = df[df['is_canceled'] == 0]

In [10]:
top_5 = successful.groupby('country')['hotel'].count().sort_values(ascending = False).head(5)

In [11]:
top_5

country
PRT    21071
GBR     9676
FRA     8481
ESP     6391
DEU     6069
Name: hotel, dtype: int64

In [12]:
nights_hotels_avg = df.groupby('hotel')['stays_total_nights'].mean()

In [13]:
nights_hotels_avg

hotel
City Hotel      2.978142
Resort Hotel    4.318547
Name: stays_total_nights, dtype: float64

In [14]:
diff_rooms = (df['reserved_room_type'] != df['assigned_room_type']).sum()

In [15]:
diff_rooms

np.int64(14917)

In [16]:
popular_2016 = successful[successful['arrival_date_year'] == 2016].groupby('arrival_date_month').size().sort_values(ascending = False).head(1)

In [17]:
popular_2016

arrival_date_month
October    3689
dtype: int64

In [18]:
popular_2017 = successful[successful['arrival_date_year'] == 2017].groupby('arrival_date_month').size().sort_values(ascending = False).head(1)

In [19]:
popular_2017

arrival_date_month
May    3551
dtype: int64

In [33]:
top_ch_cancels = df[(df['hotel'] == 'City Hotel') & (df['is_canceled'] == 1)].groupby(['arrival_date_year', 'arrival_date_month']).size().reset_index(name='cancellations') .sort_values(['arrival_date_year', 'cancellations'], ascending=[True, False]).groupby('arrival_date_year').head(1)

In [34]:
top_ch_cancels

    arrival_date_year arrival_date_month  cancellations
5                2015          September           1543
16               2016            October           1947
25               2017                May           2217

In [37]:
family = df[['adults', 'children', 'babies']]

In [41]:
family.mean().sort_values(ascending = False).head(1)

adults    1.856403
dtype: float64

In [42]:
df['total_kids'] = df['children'] + df['babies']

In [46]:
df['total_kids']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ...
119385    0.0
119386    0.0
119387    0.0
119388    0.0
119389    0.0
Name: total_kids, Length: 119390, dtype: float64

In [53]:
kids = df.groupby('hotel')['total_kids'].mean()

In [54]:
kids

hotel
City Hotel      0.096311
Resort Hotel    0.142586
Name: total_kids, dtype: float64

In [57]:
df['has_kids'] = df['total_kids'] > 0

In [63]:
churn_rate = df.groupby('has_kids')['is_canceled'].mean() * 100

In [64]:
churn_rate

has_kids
False    37.221283
True     34.922846
Name: is_canceled, dtype: float64